package com.mhf.dao;

import com.mhf.pojo.User;
import org.apache.ibatis.annotations.Param;

import java.util.List;

public interface UserMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user
     *
     * @mbg.generated
     */
    int insert(User record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user
     *
     * @mbg.generated
     */
    User selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user
     *
     * @mbg.generated
     */
    List<User> selectAll();

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(User record);

    /**
     * 检查用户名是否存在
     */
    int checkUsername(String username);

    /**
     * 根据用户名密码查询用户信息
     */
    User selectUserByUsernameAndPassword(@Param("username") String username,@Param("password") String password);

    /**
     * 检查邮箱是否存在
     */
    int checkEmail(String email);

    /**
     * 根据用户名查询密保问题
     */
    String selectQuestionByUsername(String username);

    /**
     * 验证密保答案
     */
    int checkAnswer(@Param("username") String username,@Param("question") String question,
                                        @Param("answer") String answer);

    /**
     * 修改用户密码
     */
    int updatePassword(@Param("username") String username,@Param("password") String password);

    /**
     * 更新用户信息
     */
    int updateInformation(User user);
}