package com.mhf.dao;

import com.mhf.pojo.XiaomiOrder;
import java.util.List;

public interface XiaomiOrderMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table xiaomi_order
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table xiaomi_order
     *
     * @mbg.generated
     */
    int insert(XiaomiOrder record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table xiaomi_order
     *
     * @mbg.generated
     */
    XiaomiOrder selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table xiaomi_order
     *
     * @mbg.generated
     */
    List<XiaomiOrder> selectAll();

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table xiaomi_order
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(XiaomiOrder record);
}