package com.mhf.dao;

import com.mhf.pojo.XiaomiOrder;
import org.apache.ibatis.annotations.Param;

import java.util.List;

public interface XiaomiOrderMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table xiaomi_order
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table xiaomi_order
     *
     * @mbg.generated
     */
    int insert(XiaomiOrder record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table xiaomi_order
     *
     * @mbg.generated
     */
    XiaomiOrder selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table xiaomi_order
     *
     * @mbg.generated
     */
    List<XiaomiOrder> selectAll();

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table xiaomi_order
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(XiaomiOrder record);

    /**
     * 根据orderNo和userId查询
     */
    XiaomiOrder findOrderByUserIdAndOrderNo(@Param(value = "userId") Integer userId,
                                            @Param(value = "orderNo") Long orderNo);

    /**
     * 根据userId查询订单
     */
    List<XiaomiOrder> findOrderByUserId(Integer userId);

    /**
     * 根据orderNo查询订单
     */
    XiaomiOrder findOrderByOrderNo(Long orderNo);

    /**
     * 根据创建时间查询订单
     */
    List<XiaomiOrder> findOrderByCreateTime(@Param("orderStatus") Integer orderStatus,
                                            @Param("time")String time);
}